export const DEVICES = {
  GET_DEVICES: {
    MAIN: "GET_DEVICES",
    SUCCESS: "GET_DEVICES_SUCCESS",
    FAILURE: "GET_DEVICES_FAILURE",
  },
  NOTIFY: {
    MAIN: "NOTIFY",
    SUCCESS: "NOTIFY_SUCCESS",
    FAILURE: "NOTIFY_FAILURE",
  },
};
